name: ghostcraft
description: GhostCraft - Fake Bank Slips Generator (SlipCraft Replica)

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  pdf: ^3.11.1
  share_plus: ^10.0.0
  path_provider: ^2.1.4

flutter:
  uses-material-design: true